# Generated by Django 4.0.8 on 2022-11-20 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название Карточки')),
                ('description', models.TextField(verbose_name='Описание Карточки')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Доски')),
                ('image', models.FilePathField(path='img/', verbose_name='Фон Доски')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель доски')),
            ],
            options={
                'verbose_name': 'Доска',
                'verbose_name_plural': 'Доски',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
                ('to_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='desk.desk', verbose_name='Доска')),
            ],
            options={
                'verbose_name': 'Гость Доски',
                'verbose_name_plural': 'Гости Доски',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField(verbose_name='Автор')),
                ('body', models.TextField(verbose_name='Текст Комментария')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Оставлен в: ')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='desk.card', verbose_name='К карточке: ')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название Колонки')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='desk.desk', verbose_name='Доска')),
            ],
            options={
                'verbose_name': 'Колонка',
                'verbose_name_plural': 'Колонки',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='desk.column', verbose_name='Колонка'),
        ),
    ]
