# Generated by Django 4.0.8 on 2022-11-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_alter_desk_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='image',
            field=models.ImageField(upload_to='desk-uploads/', verbose_name='Фон Доски'),
        ),
    ]
