# Generated by Django 4.0.8 on 2022-11-23 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0010_alter_card_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дедлайн'),
        ),
    ]
