# Generated by Django 4.0.8 on 2022-11-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0011_alter_card_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deadline',
            field=models.DateField(verbose_name='Дедлайн'),
        ),
    ]
