# Generated by Django 4.0.8 on 2022-11-23 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desk', '0013_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit', models.DateTimeField(auto_now_add=True, verbose_name='Последний визит в: ')),
                ('to_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_visits', to='desk.desk', verbose_name='Доска')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_visits', to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
            options={
                'verbose_name': 'Последний Визит',
                'verbose_name_plural': 'Последние Визиты',
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='desk.desk', verbose_name='Доска')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
            options={
                'verbose_name': 'Архивированная Доска',
                'verbose_name_plural': 'Архивированные Доски',
            },
        ),
    ]
